(()=>{
const style=document.createElement('style');style.textContent=`#tnm-chat-bubble{position:fixed;right:20px;bottom:20px;width:58px;height:58px;border:0;border-radius:50%;background:#2A9D8F;color:#fff;font-size:23px;box-shadow:0 12px 35px #26465330;z-index:9999;cursor:pointer}#tnm-chat{position:fixed;right:20px;bottom:88px;width:min(380px,calc(100vw - 28px));height:min(520px,calc(100vh - 115px));background:#fff;border:1px solid #dfe9e7;border-radius:20px;box-shadow:0 22px 70px #26465325;z-index:9999;display:flex;flex-direction:column;overflow:hidden;font-family:system-ui,-apple-system,BlinkMacSystemFont,sans-serif}#tnm-chat .head{padding:16px 17px;background:#264653;color:#fff;display:flex;justify-content:space-between;align-items:center}#tnm-chat .head b{display:block;font-size:16px}#tnm-chat .head span{display:block;color:#cfdbdd;font-size:11px;margin-top:3px}#tnm-chat .head button{background:transparent;color:#fff;padding:0;font-size:23px}#tnm-chat .msgs{flex:1;overflow:auto;padding:15px;background:#f7fbfa}#tnm-chat .msg{max-width:84%;padding:10px 12px;border-radius:14px;margin:7px 0;font-size:13px;line-height:1.45;white-space:pre-wrap}#tnm-chat .assistant{background:#eef8f6;color:#264653;margin-right:auto}#tnm-chat .user{background:#2A9D8F;color:#fff;margin-left:auto}#tnm-chat .input{display:flex;gap:8px;padding:11px;border-top:1px solid #dfe9e7;background:#fff}#tnm-chat input{flex:1;min-width:0;border:1px solid #cfdedb;border-radius:11px;padding:11px 12px;outline:none;font-size:14px}#tnm-chat .input button{background:#264653;color:#fff;border-radius:11px;padding:10px 14px}@media(max-width:560px){#tnm-chat{right:12px;bottom:80px}#tnm-chat-bubble{right:14px;bottom:14px}}`;document.head.appendChild(style);
const bubble=document.createElement('button');bubble.id='tnm-chat-bubble';bubble.setAttribute('aria-label','Open chat');bubble.textContent='💬';document.body.appendChild(bubble);
const panel=document.createElement('div');panel.id='tnm-chat';panel.style.display='none';panel.innerHTML='<div class="head"><div><b>TalkNMe</b><span>Ask anything</span></div><button aria-label="Close">×</button></div><div class="msgs"></div><div class="input"><input placeholder="Ask anything…" autocomplete="off"><button>Send</button></div>';document.body.appendChild(panel);
const msgs=panel.querySelector('.msgs'),input=panel.querySelector('input'),send=panel.querySelector('.input button');let history=[{role:'assistant',content:'Hi! What can I help you with? You can ask me anything.'}];
function render(){msgs.innerHTML=history.map(m=>`<div class="msg ${m.role}">${String(m.content).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div>`).join('');msgs.scrollTop=msgs.scrollHeight}
async function ask(){const text=input.value.trim();if(!text)return;history.push({role:'user',content:text});input.value='';render();send.disabled=true;history.push({role:'assistant',content:'Thinking…'});render();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.slice(0,-1)})});const d=await r.json();history.pop();history.push({role:'assistant',content:d.answer||d.error||'I could not answer that right now.'});}catch(e){history.pop();history.push({role:'assistant',content:'Something went wrong. Please try again.'});}finally{send.disabled=false;render();}}
bubble.onclick=()=>{const open=panel.style.display==='flex';panel.style.display=open?'none':'flex';bubble.textContent=open?'💬':'×';if(!open){render();input.focus()}};panel.querySelector('.head button').onclick=()=>{panel.style.display='none';bubble.textContent='💬'};send.onclick=ask;input.onkeydown=e=>{if(e.key==='Enter')ask()};
})();
